# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('newtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('body_template', models.TextField(default=b'Happy Birthday {{Name}}!, from {{Doctor}}.', verbose_name=b'email message template')),
                ('subject_template', models.CharField(default=b'Happy Birthday!', max_length=100, verbose_name=b'email subject template')),
            ],
        ),
    ]
