# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0002_emailtemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name=b'Send Messages'),
        ),
    ]
