# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0003_emailtemplates_send_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='expires',
            new_name='expires_at',
        ),
    ]
