# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0004_auto_20160310_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.FloatField(),
        ),
    ]
